server:
  port: 3000


spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oduorsamuel/config-server
          clone-on-start: true
          default-label: main
