server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/

  datasource:
    url: jdbc:mysql://localhost:3306/employees_details
    username: root